# Generated by Django 2.2.1 on 2019-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_bugs', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '>10')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('1', 'dolnośląskie'), ('2', 'kujawsko-pomorskie'), ('3', 'lubelskie'), ('4', 'lubuskie'), ('5', 'łódzkie'), ('6', 'małopolskie'), ('7', 'mazowieckie'), ('8', 'opolskie'), ('9', 'podkarpackie'), ('10', 'podlaskie'), ('11', 'pomorskie'), ('12', 'śląskie'), ('13', 'świętokrzyskie'), ('14', 'warmińsko-mazurskie'), ('15', 'wielkopolskie'), ('16', 'zachodniopomorskie')], max_length=50)),
                ('help', models.CharField(choices=[('1', 'dzieciom'), ('2', 'samotnym matkom'), ('3', 'bezdomnym'), ('4', 'niepełnosprawnym'), ('5', 'osobom starszym'), ('6', 'bezrobotnym')], max_length=100)),
                ('charity', models.CharField(max_length=255)),
            ],
        ),
    ]
