# Generated by Django 2.2.1 on 2019-05-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bags_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=6)),
                ('phone', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='Charity',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='charity',
            new_name='charity_name',
        ),
    ]
