# Generated by Django 2.2.1 on 2019-05-27 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190523_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_who', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='charity',
            name='help',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Help'),
        ),
    ]
