# Generated by Django 2.2.1 on 2019-05-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190527_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='help',
        ),
        migrations.AddField(
            model_name='charity',
            name='help',
            field=models.ManyToManyField(to='core.Help'),
        ),
    ]
