# Generated by Django 2.2.1 on 2019-05-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190527_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='help',
        ),
        migrations.AddField(
            model_name='charity',
            name='help',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Help'),
        ),
    ]
