# Generated by Django 2.2.1 on 2019-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190527_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='help',
        ),
        migrations.AddField(
            model_name='charity',
            name='help',
            field=models.ManyToManyField(to='core.Help'),
        ),
    ]
