# Generated by Django 2.2.1 on 2019-05-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190527_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='for_who',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
