# Generated by Django 2.2.1 on 2019-06-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190528_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.CharField(choices=[('1', 'dla dorosłych'), ('2', 'dla dzieci'), ('3', 'dla młodzieży'), ('4', 'edukacyjne')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('others', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toys', models.CharField(choices=[('1', 'Chłopiec'), ('2', 'Dziewczynka')], max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='books',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='others',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='toys',
        ),
        migrations.AddField(
            model_name='address',
            name='more_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bags',
            name='number_of_bugs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='for_who',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='purpose',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Address')),
                ('bags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bags')),
                ('books', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Books')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Charity')),
                ('clothes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Clothes')),
                ('others', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Others')),
                ('toys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Toys')),
            ],
        ),
    ]
