# Generated by Django 2.2.1 on 2019-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190604_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='for_who',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='purpose',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
