# Generated by Django 2.2.1 on 2019-06-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190604_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='books',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='others',
            name='others',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='toys',
            name='toys',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
