# Generated by Django 2.2.1 on 2019-06-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190604_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
