# Generated by Django 2.2.1 on 2019-06-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='UselessClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useless_clothes', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='donate',
            name='useless_clothes',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.UselessClothes'),
        ),
    ]
