# Generated by Django 2.2.1 on 2019-06-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190604_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='useless_clothes',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UselessClothes',
        ),
    ]
