# Generated by Django 2.2.1 on 2019-06-04 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190604_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='form_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 6, 4, 13, 19, 32, 98076)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donate',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Odebrany'),
        ),
        migrations.AddField(
            model_name='donate',
            name='status_change',
            field=models.DateTimeField(auto_now=True, verbose_name='status'),
        ),
    ]
