# Generated by Django 2.2.1 on 2019-06-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190604_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='status_change',
            field=models.DateTimeField(null=True, verbose_name='status'),
        ),
    ]
